// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mulakat.Data.Context;

namespace Mulakat.Data.Migrations
{
    [DbContext(typeof(MulakatContext))]
    [Migration("20210319085928_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mulakat.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            ID = new Guid("43155072-0b94-4c98-a718-e05e01095d17"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 338, DateTimeKind.Local).AddTicks(9119),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 338, DateTimeKind.Local).AddTicks(9150),
                            Poster = "https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
                            Title = "Batman Begins",
                            Year = "2005"
                        },
                        new
                        {
                            ID = new Guid("4f886738-f6ec-43a4-9879-491ce28284b0"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1263),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1289),
                            Poster = "https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
                            Title = "Batman v Superman: Dawn of Justice",
                            Year = "2016"
                        },
                        new
                        {
                            ID = new Guid("280073c1-b23f-4fd4-9cb4-7833407df3f6"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1598),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1601),
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg",
                            Title = "Batman",
                            Year = "1989"
                        },
                        new
                        {
                            ID = new Guid("cd62d581-cf0d-4d13-bc0f-2043d13c35c9"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1651),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1652),
                            Poster = "https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg",
                            Title = "Batman Returns",
                            Year = "1992"
                        },
                        new
                        {
                            ID = new Guid("09958524-27dd-44e3-b792-fd1d9e8b148a"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1693),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(1695),
                            Poster = "https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg",
                            Title = "Batman & Robin",
                            Year = "1997"
                        },
                        new
                        {
                            ID = new Guid("5ee056a4-a047-4a2f-b29f-f2cd27305d7e"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2604),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2610),
                            Poster = "https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
                            Title = "Batman Forever",
                            Year = "1995"
                        },
                        new
                        {
                            ID = new Guid("a8e0937a-b77c-43c2-8e43-35c944d291ca"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2656),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2657),
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg",
                            Title = "The Lego Batman Movie",
                            Year = "2017"
                        },
                        new
                        {
                            ID = new Guid("e8940858-8af4-4139-86cd-dde9a1aab0c7"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2741),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2742),
                            Poster = "https://m.media-amazon.com/images/M/MV5BOTM3MTRkZjQtYjBkMy00YWE1LTkxOTQtNDQyNGY0YjYzNzAzXkEyXkFqcGdeQXVyOTgwMzk1MTA@._V1_SX300.jpg",
                            Title = "Batman: The Animated Series",
                            Year = "1992–1995"
                        },
                        new
                        {
                            ID = new Guid("b334a170-3323-42b9-9091-5d9a96a66650"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2783),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(2784),
                            Poster = "https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
                            Title = "Batman: Under the Red Hood",
                            Year = "2010"
                        },
                        new
                        {
                            ID = new Guid("f774677b-9f72-4de5-8857-5e969259b5ec"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(4063),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ModifiedDate = new DateTime(2021, 3, 19, 11, 59, 28, 356, DateTimeKind.Local).AddTicks(4069),
                            Poster = "https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg",
                            Title = "Batman: The Dark Knight Returns, Part 1",
                            Year = "2012"
                        });
                });

            modelBuilder.Entity("Mulakat.Data.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
